name: Python application

on:
  push:
    branches: [ "API" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: 'API'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Add SSH Key for Heroku
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.HEROKU_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
        git remote add heroku git@heroku.com:dsoc-p7-api.git

    - name: Deploy to Heroku
      run: |
        git push heroku API:master

    - name: Run Tests
      run: |
        pytest -vv